src/Entity/Branch.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BranchRepository")
 */
class Branch
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="branches")
     */
    private $Company;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $oic;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
    
    public function getCompany(): ?Company
    {
        return $this->Company;
    }

    public function setCompany(?Company $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getOic(): ?string
    {
        return $this->oic;
    }

    public function setOic(string $oic): self
    {
        $this->oic = $oic;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }
}

src/Form/BranchType.php
<?php

namespace App\Form;

use App\Entity\Branch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class BranchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('oic')
            ->add('CreatedAt')
            ->add('Company')
            ->add('attachment', FileType::class, [
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Branch::class,
        ]);
    }
}

src/Controller/BranchController.php
<?php

namespace App\Controller;

use App\Entity\Branch;
use App\Form\BranchType;
use App\Repository\BranchRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/branch")
 */
class BranchController extends AbstractController
{
    /**
     * @Route("/", name="branch_index", methods={"GET"})
     */
    public function index(BranchRepository $branchRepository): Response
    {
        return $this->render('branch/index.html.twig', [
            'branches' => $branchRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="branch_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $branch = new Branch();
        $form = $this->createForm(BranchType::class, $branch);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $request->files->get('branch')['attachment'];
            if($file) {
                $filename = md5(uniqid()) . '.' . $file->guessClientExtension();

                $file->move(
                    $this->getParameter('uploads_dir'),
                    $filename
                );
            }
           
            $entityManager = $this->getDoctrine()->getManager();
            $branch->setImage($filename);
            $entityManager->persist($branch);
            $entityManager->flush();

            return $this->redirectToRoute('branch_index');
        }

        return $this->render('branch/new.html.twig', [
            'branch' => $branch,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="branch_show", methods={"GET"})
     */
    public function show(Branch $branch): Response
    {
        return $this->render('branch/show.html.twig', [
            'branch' => $branch,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="branch_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Branch $branch): Response
    {
        $form = $this->createForm(BranchType::class, $branch);
        $form->handleRequest($request);
 
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $request->files->get('branch')['attachment'];
            if($file) {
                $filename = md5(uniqid()) . '.' . $file->guessClientExtension();

                $file->move(
                    $this->getParameter('uploads_dir'),
                    $filename
                );
            }
           
            $branch->setImage($filename);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('branch_index');
        }

        return $this->render('branch/edit.html.twig', [
            'branch' => $branch,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="branch_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Branch $branch): Response
    {
        //if ($this->isCsrfTokenValid('delete'.$branch->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($branch);
            $entityManager->flush();
        //}

        return $this->redirect($this->generateUrl('branch_index'));
        //return $this->redirectToRoute('branch_index');
    }
}

templates/branch/_delete_form.html.twig
<form method="post" action="{{ path('branch_delete', {'id': branch.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ branch.id) }}">
    <button class="btn">Delete</button>
</form>

templates/branch/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/branch/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Branch{% endblock %}

{% block body %}
    <h1>Edit Branch</h1>

    {{ include('branch/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('branch_index') }}">back to list</a>

    {{ include('branch/_delete_form.html.twig') }}
{% endblock %}

templates/branch/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Branch index{% endblock %}

{% block body %}
    <h1>Branch List</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Branch Name</th>
                <th>OIC</th>
                <th>Company</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for branch in branches %}
            <tr>
                <td>{{ branch.id }}</td>
                <td>{{ branch.name }}</td>
                <td>{{ branch.oic }}</td>
                <td>{{ branch.company.name }}</td>
                <td>
                    <a href="{{ path('branch_show', {'id': branch.id}) }}">show</a>
                    <a href="{{ path('branch_edit', {'id': branch.id}) }}">edit</a>
                    <a href="{{ path('branch_delete', {'id': branch.id}) }}">delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('branch_new') }}">Create new</a>
{% endblock %}

templates/branch/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Branch{% endblock %}

{% block body %}
    <h1>Create new Branch</h1>

    {{ include('branch/_form.html.twig') }}

    <a href="{{ path('branch_index') }}">back to list</a>
{% endblock %}

templates/branch/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Branch{% endblock %}

{% block body %}
    {% apply inline_css %}
        <style>
            img { width: 10%; }
        </style>
    {% endapply %}    
    <h1>Branch</h1>

    <table class="table">
        <tbody>
             <tr>
                <th>Image</th>
                <td><img src="{{ 'http://localhost/sfcourse/public/uploads/' ~ branch.image }}" alt=""></td>
            </tr>
        
            <tr>
                <th>Id</th>
                <td>{{ branch.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ branch.name }}</td>
            </tr>
            <tr>
                <th>Oic</th>
                <td>{{ branch.oic }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ branch.CreatedAt ? branch.CreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('branch_index') }}">back to list</a>

    <a href="{{ path('branch_edit', {'id': branch.id}) }}">edit</a>

    {{ include('branch/_delete_form.html.twig') }}
    
{% endblock %}